<a href="https://colab.research.google.com/github/ledyquesada/Ejercicios/blob/main/Semana14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# VALIDACIÓN CRUZADA
**K-Fold**

In [3]:
#K-Fold
from sklearn.model_selection import cross_val_score, KFold
from sklearn.linear_model import LinearRegression
import numpy as np

# Datos de ejemplo
X = np.random.rand(100, 5)
y = 2*X[:, 0] + 3*X[:, 1] + np.random.randn(100)

# Modelo de regresión lineal
modelo = LinearRegression()

# K-Fold Cross-Validation con 5 folds
kf = KFold(n_splits=5, shuffle=True, random_state=42)
resultados = cross_val_score(modelo, X, y, cv=kf)

# Imprimir resultados
print("Resultados K-Fold Cross-Validation:")
print(resultados)

#Stratified K-Fold
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.datasets import make_classification

# Datos de ejemplo desequilibrados
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, weights=[0.95, 0.05], random_state=42)

# Modelo de SVM
modelo_svm = SVC(kernel='linear')

# Stratified K-Fold Cross-Validation con 3 folds
skf = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)
resultados_stratified = cross_val_score(modelo_svm, X, y, cv=skf)

# Imprimir resultados
print("Resultados Stratified K-Fold Cross-Validation:")
print(resultados_stratified)

#Leave-One-Out Cross-Validation

from sklearn.model_selection import LeaveOneOut
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_iris

# Datos de ejemplo (iris)
iris = load_iris()
X, y = iris.data, iris.target

# Modelo de clasificación k-NN
modelo_knn = KNeighborsClassifier()

# Leave-One-Out Cross-Validation
loo = LeaveOneOut()
resultados_loo = cross_val_score(modelo_knn, X, y, cv=loo)

# Imprimir resultados
print("Resultados Leave-One-Out Cross-Validation:")
print(resultados_loo)


Resultados K-Fold Cross-Validation:
[ 0.49058583  0.48907417 -0.0314514   0.5469021   0.55665921]
Resultados Stratified K-Fold Cross-Validation:
[0.9491018  0.95195195 0.95195195]
Resultados Leave-One-Out Cross-Validation:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


**EJEMPLO PRACTICO**
En este ejemplo, se utiliza un conjunto de datos aleatorio generado por make_classification de Scikit-Learn. El modelo de clasificación utilizado es un Bosque Aleatorio (RandomForestClassifier). Se aplica K-Fold Cross-Validation con 5 folds para evaluar el rendimiento del modelo. Los resultados impresos son las puntuaciones de la validación cruzada para cada fold.


In [4]:
from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

# Generar un conjunto de datos aleatorio
X, y = make_classification(n_samples=1000, n_features=20, n_classes=2, random_state=42)

# Modelo de clasificación - Bosques Aleatorios
modelo_rf = RandomForestClassifier(n_estimators=100, random_state=42)

# K-Fold Cross-Validation con 5 folds
kf = KFold(n_splits=5, shuffle=True, random_state=42)

# Resultados de la validación cruzada
resultados = cross_val_score(modelo_rf, X, y, cv=kf)

# Imprimir resultados
print("Resultados de K-Fold Cross-Validation:")
print(resultados)


Resultados de K-Fold Cross-Validation:
[0.895 0.86  0.935 0.88  0.925]
